name: 'Lines Changed Summary'
description: 'Comment on PRs with a lines changed summary, ignoring specified file patterns'
author: 'Your Name'
branding:
  icon: 'bar-chart-2'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  ignore-patterns:
    description: 'Comma-separated list of file patterns to ignore (e.g., "**/generated/**,**/*.generated.ts")'
    required: false
    default: ''
  comment-header:
    description: 'Optional text to display above the summary (leave empty for default)'
    required: false
    default: ''

outputs:
  added-lines:
    description: 'Number of lines added (not counting ignored files)'
  removed-lines:
    description: 'Number of lines removed (not counting ignored files)'
  total-files:
    description: 'Total number of files changed'
  ignored-files:
    description: 'Number of files ignored by patterns'

runs:
  using: 'node20'
  main: 'dist/index.js'
