import * as esbuild from 'esbuild';

await esbuild.build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  outfile: 'dist/index.js',
  sourcemap: true,
  format: 'cjs',
  minify: false,
  external: [],
  banner: {
    js: '// Generated by esbuild',
  },
});

console.log('✓ Build complete');
