import { describe, it, expect } from 'vitest';
import { generateCommentBody } from '../generateCommentBody';
import { COMMENT_IDENTIFIER } from '../constants';
import type { DiffSummary } from '../types';

describe('generateCommentBody', () => {
  const createSummary = (
    overrides: Partial<DiffSummary> = {}
  ): DiffSummary => ({
    addedLines: 100,
    removedLines: 50,
    ignoredAddedLines: 0,
    ignoredRemovedLines: 0,
    totalFiles: 2,
    includedFiles: [
      {
        filename: 'src/main.ts',
        additions: 70,
        deletions: 30,
        changes: 100,
        status: 'modified',
      },
      {
        filename: 'src/utils.ts',
        additions: 30,
        deletions: 20,
        changes: 50,
        status: 'modified',
      },
    ],
    ignoredFiles: [],
    ...overrides,
  });

  it('should include comment identifier', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain(COMMENT_IDENTIFIER);
  });

  it('should show correct line counts', () => {
    const body = generateCommentBody(
      createSummary({ addedLines: 342, removedLines: 128 }),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('**+342**');
    expect(body).toContain('**-128**');
  });

  it('should prepend custom header above the summary when provided', () => {
    const body = generateCommentBody(
      createSummary(),
      '### Custom Context',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('### Custom Context');
    // The squares header should still be present
    expect(body).toMatch(/## .+\*\*\+100\*\*/);
  });

  it('should include changed files section', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Changed (2 files');
    expect(body).toContain('src/main.ts');
    expect(body).toContain('src/utils.ts');
  });

  it('should include ignored files section when files are ignored', () => {
    const summary = createSummary({
      ignoredFiles: [
        {
          filename: 'dist/index.js',
          additions: 400,
          deletions: 50,
          changes: 450,
          status: 'modified',
        },
        {
          filename: 'generated/api.ts',
          additions: 100,
          deletions: 50,
          changes: 150,
          status: 'modified',
        },
      ],
      ignoredAddedLines: 500,
      ignoredRemovedLines: 100,
    });

    const body = generateCommentBody(
      summary,
      '',
      ['**/dist/**', '**/generated/**'],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Ignored (2 files');
    expect(body).toContain('dist/index.js');
    expect(body).toContain('generated/api.ts');
    expect(body).toContain('**/dist/**');
  });

  it('should not include ignored section when no files ignored', () => {
    const body = generateCommentBody(
      createSummary({ ignoredFiles: [] }),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).not.toContain('Ignored (');
  });

  it('should calculate percentages correctly', () => {
    const summary = createSummary({
      addedLines: 85,
      removedLines: 15,
      ignoredAddedLines: 0,
      ignoredRemovedLines: 0,
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    expect(body).toContain('100% of changes');
  });

  it('should sort files by changes descending', () => {
    const summary = createSummary({
      includedFiles: [
        {
          filename: 'small.ts',
          additions: 10,
          deletions: 5,
          changes: 15,
          status: 'modified',
        },
        {
          filename: 'large.ts',
          additions: 100,
          deletions: 50,
          changes: 150,
          status: 'modified',
        },
        {
          filename: 'medium.ts',
          additions: 30,
          deletions: 20,
          changes: 50,
          status: 'modified',
        },
      ],
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    const largeIndex = body.indexOf('large.ts');
    const mediumIndex = body.indexOf('medium.ts');
    const smallIndex = body.indexOf('small.ts');

    expect(largeIndex).toBeLessThan(mediumIndex);
    expect(mediumIndex).toBeLessThan(smallIndex);
  });

  it('should include attribution footer', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Generated by');
    expect(body).toContain('Lines Changed');
    expect(body).toContain('https://github.com/nrutman/lines-changed-gha');
  });

  it('should handle singular file count', () => {
    const summary = createSummary({
      includedFiles: [
        {
          filename: 'only.ts',
          additions: 10,
          deletions: 5,
          changes: 15,
          status: 'modified',
        },
      ],
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    expect(body).toContain('1 file');
    expect(body).not.toContain('1 files');
  });

  it('should generate valid file diff URLs', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain(
      'https://github.com/owner/repo/pull/123/files#diff-'
    );
  });

  it('should handle empty PR with no files', () => {
    const summary = createSummary({
      addedLines: 0,
      removedLines: 0,
      includedFiles: [],
      ignoredFiles: [],
      totalFiles: 0,
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    expect(body).toContain('**+0** / **-0**');
    expect(body).not.toContain('Changed (');
    expect(body).not.toContain('Ignored (');
    expect(body).toContain('Generated by');
  });
});
