import { describe, expect, it } from 'vitest';
import { COMMENT_IDENTIFIER } from '../constants';
import { generateCommentBody } from '../generateCommentBody';
import type {
  DiffSummary,
  FileChange,
  FileGroup,
  GroupedFiles,
} from '../types';

describe('generateCommentBody', () => {
  // Helper to create a file change
  const file = (
    filename: string,
    additions: number,
    deletions: number
  ): FileChange => ({
    filename,
    additions,
    deletions,
    changes: additions + deletions,
    status: 'modified',
  });

  // Helper to create a grouped files entry for a defined group (with patterns)
  const groupedFiles = (
    label: string,
    patterns: string[],
    files: FileChange[],
    countTowardMetric = true,
    ignoreWhitespace = false
  ): GroupedFiles => {
    const group: FileGroup = {
      label,
      patterns,
      countTowardMetric,
      ignoreWhitespace,
    };
    return {
      group,
      files,
      addedLines: files.reduce((sum, f) => sum + f.additions, 0),
      removedLines: files.reduce((sum, f) => sum + f.deletions, 0),
    };
  };

  // Helper to create a grouped files entry for the default group (no patterns)
  const defaultGroupedFiles = (
    label: string,
    files: FileChange[]
  ): GroupedFiles => ({
    group: { label, countTowardMetric: true },
    files,
    addedLines: files.reduce((sum, f) => sum + f.additions, 0),
    removedLines: files.reduce((sum, f) => sum + f.deletions, 0),
  });

  // Helper to create a summary
  const summary = (
    groups: GroupedFiles[],
    overrides: Partial<DiffSummary> = {}
  ): DiffSummary => {
    const countedGroups = groups.filter(g => g.group.countTowardMetric);
    const uncountedGroups = groups.filter(g => !g.group.countTowardMetric);

    return {
      addedLines: countedGroups.reduce((sum, g) => sum + g.addedLines, 0),
      removedLines: countedGroups.reduce((sum, g) => sum + g.removedLines, 0),
      uncountedAddedLines: uncountedGroups.reduce(
        (sum, g) => sum + g.addedLines,
        0
      ),
      uncountedRemovedLines: uncountedGroups.reduce(
        (sum, g) => sum + g.removedLines,
        0
      ),
      totalFiles: groups.reduce((sum, g) => sum + g.files.length, 0),
      groupedFiles: groups,
      ...overrides,
    };
  };

  // Helper to generate comment with defaults
  const generate = (s: DiffSummary, header = '') =>
    generateCommentBody(s, header, 'owner', 'repo', 123, 'abc1234def5678');

  describe('basic structure', () => {
    const basicSummary = summary([
      defaultGroupedFiles('Changed', [
        file('src/main.ts', 100, 50),
        file('src/utils.ts', 30, 20),
      ]),
    ]);

    it('should include comment identifier for update detection', () => {
      const body = generate(basicSummary);
      expect(body).toContain(COMMENT_IDENTIFIER);
    });

    it('should show correct line counts in header', () => {
      const body = generate(basicSummary);
      expect(body).toContain('**+130**');
      expect(body).toContain('**-70**');
    });

    it('should include attribution footer with commit link', () => {
      const body = generate(basicSummary);
      expect(body).toContain('Generated by');
      expect(body).toContain('Lines Changed');
      expect(body).toContain('abc1234');
      expect(body).toContain(
        'https://github.com/owner/repo/commit/abc1234def5678'
      );
    });

    it('should generate valid file diff URLs', () => {
      const body = generate(basicSummary);
      expect(body).toContain(
        'https://github.com/owner/repo/pull/123/files#diff-'
      );
    });

    it('should prepend custom header when provided', () => {
      const body = generate(basicSummary, '### Custom Context');
      expect(body).toContain('### Custom Context');
      expect(body).toMatch(/## .+\*\*\+130\*\*/);
    });
  });

  describe('group sections', () => {
    it('should create collapsible section for each group with files', () => {
      const s = summary([
        groupedFiles('Source', ['src/**/*.ts'], [file('src/main.ts', 100, 50)]),
        groupedFiles(
          'Generated',
          ['**/generated/**'],
          [file('src/generated/api.ts', 500, 100)],
          false
        ),
      ]);

      const body = generate(s);

      expect(body).toContain('Source (1 file');
      expect(body).toContain('Generated (1 file, 80% of changes)*');
      expect(body).toContain('src/main.ts');
      expect(body).toContain('src/generated/api.ts');
    });

    it('should show patterns for groups that have them', () => {
      const s = summary([
        groupedFiles(
          'Generated',
          ['**/generated/**', '**/*.gen.ts'],
          [file('src/generated/api.ts', 500, 100)],
          false
        ),
      ]);

      const body = generate(s);

      expect(body).toContain('Patterns: `**/generated/**`, `**/*.gen.ts`');
    });

    it('should not show patterns for default group', () => {
      const s = summary([
        defaultGroupedFiles('Changed', [file('src/main.ts', 100, 50)]),
      ]);

      const body = generate(s);

      expect(body).not.toContain('Patterns:');
    });

    it('should handle singular vs plural file count', () => {
      const singleFile = summary([
        defaultGroupedFiles('Changed', [file('only.ts', 10, 5)]),
      ]);
      const multipleFiles = summary([
        defaultGroupedFiles('Changed', [
          file('a.ts', 10, 5),
          file('b.ts', 10, 5),
        ]),
      ]);

      expect(generate(singleFile)).toContain('1 file');
      expect(generate(singleFile)).not.toContain('1 files');
      expect(generate(multipleFiles)).toContain('2 files');
    });

    it('should sort files by changes descending within each group', () => {
      const s = summary([
        defaultGroupedFiles('Changed', [
          file('small.ts', 10, 5),
          file('large.ts', 100, 50),
          file('medium.ts', 30, 20),
        ]),
      ]);

      const body = generate(s);

      const largeIndex = body.indexOf('large.ts');
      const mediumIndex = body.indexOf('medium.ts');
      const smallIndex = body.indexOf('small.ts');

      expect(largeIndex).toBeLessThan(mediumIndex);
      expect(mediumIndex).toBeLessThan(smallIndex);
    });
  });

  describe('counting indicator', () => {
    it('should show asterisk and footnote when there are mixed counted/uncounted groups', () => {
      const s = summary([
        groupedFiles('Source', ['src/**'], [file('src/main.ts', 100, 50)]),
        groupedFiles(
          'Generated',
          ['**/generated/**'],
          [file('generated/api.ts', 500, 100)],
          false
        ),
      ]);

      const body = generate(s);

      // Uncounted group should have asterisk at end of summary
      expect(body).toContain('of changes)*');
      // Counted group should not have asterisk
      expect(body).not.toMatch(/Source.*\)\*/);
      // Footnote should appear
      expect(body).toContain('* *Not counted toward the main +/- metric*');
    });

    it('should place footnote after separator and before attribution', () => {
      const s = summary([
        groupedFiles('Source', ['src/**'], [file('src/main.ts', 100, 50)]),
        groupedFiles(
          'Generated',
          ['**/generated/**'],
          [file('generated/api.ts', 500, 100)],
          false
        ),
      ]);

      const body = generate(s);

      // Verify order: separator -> footnote -> attribution
      const separatorIndex = body.indexOf('---');
      const footnoteIndex = body.indexOf('Not counted toward the main');
      const attributionIndex = body.indexOf('Generated by');

      expect(separatorIndex).toBeGreaterThan(-1);
      expect(footnoteIndex).toBeGreaterThan(-1);
      expect(attributionIndex).toBeGreaterThan(-1);
      expect(separatorIndex).toBeLessThan(footnoteIndex);
      expect(footnoteIndex).toBeLessThan(attributionIndex);
    });

    it('should not show asterisk or footnote when all groups are counted', () => {
      const s = summary([
        groupedFiles('Source', ['src/**'], [file('src/main.ts', 100, 50)]),
        groupedFiles('Tests', ['**/*.test.ts'], [file('main.test.ts', 50, 10)]),
      ]);

      const body = generate(s);

      expect(body).not.toContain('changes)*');
      expect(body).not.toContain('Not counted');
    });

    it('should not show asterisk or footnote when all groups are uncounted', () => {
      const s = summary([
        groupedFiles(
          'Build',
          ['dist/**'],
          [file('dist/index.js', 1000, 500)],
          false
        ),
        groupedFiles(
          'Lock',
          ['*-lock.*'],
          [file('pnpm-lock.yaml', 100, 50)],
          false
        ),
      ]);

      const body = generate(s);

      // When all are uncounted, no need to call out individual ones
      expect(body).not.toContain('changes)*');
      expect(body).not.toContain('Not counted');
    });
  });

  describe('whitespace indicator', () => {
    it('should show dagger and footnote for groups with ignoreWhitespace', () => {
      const s = summary([
        groupedFiles(
          'Source',
          ['src/**'],
          [file('src/main.ts', 100, 50)],
          true,
          true
        ),
      ]);

      const body = generate(s);

      // Group should have dagger marker
      expect(body).toContain('of changes)†');
      // Footnote should appear
      expect(body).toContain(
        '† *Whitespace-only changes are excluded from counts*'
      );
    });

    it('should not show dagger for groups without ignoreWhitespace', () => {
      const s = summary([
        groupedFiles('Source', ['src/**'], [file('src/main.ts', 100, 50)]),
      ]);

      const body = generate(s);

      expect(body).not.toContain('†');
      expect(body).not.toContain('Whitespace-only changes');
    });

    it('should show both asterisk and dagger when both indicators apply', () => {
      const s = summary([
        groupedFiles(
          'Source',
          ['src/**'],
          [file('src/main.ts', 100, 50)],
          true,
          false
        ),
        groupedFiles(
          'Generated',
          ['**/generated/**'],
          [file('generated/api.ts', 500, 100)],
          false,
          true
        ),
      ]);

      const body = generate(s);

      // Generated group should have both markers
      expect(body).toContain('of changes)*†');
      // Both footnotes should appear
      expect(body).toContain('Not counted toward the main +/- metric');
      expect(body).toContain(
        'Whitespace-only changes are excluded from counts'
      );
    });
  });

  describe('percentages', () => {
    it('should calculate percentages correctly', () => {
      const s = summary([
        defaultGroupedFiles('Changed', [file('src/main.ts', 100, 50)]),
      ]);

      const body = generate(s);

      expect(body).toContain('100% of changes');
    });

    it('should show proportional percentages for multiple groups', () => {
      const s = summary([
        groupedFiles('Source', ['src/**'], [file('src/main.ts', 75, 25)]), // 100 changes
        groupedFiles(
          'Generated',
          ['dist/**'],
          [file('dist/index.js', 225, 75)], // 300 changes
          false
        ),
      ]);

      const body = generate(s);

      // Source: 100/400 = 25%
      // Generated: 300/400 = 75%
      expect(body).toContain('25% of changes');
      expect(body).toContain('75% of changes');
    });
  });

  describe('edge cases', () => {
    it('should handle empty PR with no files', () => {
      const s = summary([]);

      const body = generate(s);

      expect(body).toContain('**+0** / **-0**');
      expect(body).not.toContain('Changed (');
      expect(body).toContain('Generated by');
    });

    it('should handle PR where all files are in uncounted groups', () => {
      const s = summary([
        groupedFiles(
          'Generated',
          ['dist/**'],
          [file('dist/index.js', 1000, 500)],
          false
        ),
      ]);

      const body = generate(s);

      expect(body).toContain('**+0** / **-0**');
      expect(body).toContain('Generated (1 file');
    });

    it('should support emoji in group labels', () => {
      const s = summary([
        groupedFiles(
          '🧪 Tests',
          ['**/*.test.ts'],
          [file('main.test.ts', 50, 10)]
        ),
        groupedFiles(
          '📦 Build',
          ['dist/**'],
          [file('dist/index.js', 1000, 500)],
          false
        ),
        defaultGroupedFiles('🏅 Source Code', [file('src/main.ts', 100, 50)]),
      ]);

      const body = generate(s);

      expect(body).toContain('🧪 Tests');
      expect(body).toContain('📦 Build');
      expect(body).toContain('🏅 Source Code');
    });
  });
});
