import { describe, it, expect } from 'vitest';
import { generateCommentBody } from '../generateCommentBody';
import { COMMENT_IDENTIFIER } from '../constants';
import type { DiffSummary } from '../types';

describe('generateCommentBody', () => {
  const createSummary = (
    overrides: Partial<DiffSummary> = {}
  ): DiffSummary => ({
    addedLines: 100,
    removedLines: 50,
    excludedAddedLines: 0,
    excludedRemovedLines: 0,
    totalFiles: 2,
    excludedFiles: [],
    includedFiles: [
      {
        filename: 'src/main.ts',
        additions: 70,
        deletions: 30,
        changes: 100,
        status: 'modified',
      },
      {
        filename: 'src/utils.ts',
        additions: 30,
        deletions: 20,
        changes: 50,
        status: 'modified',
      },
    ],
    ...overrides,
  });

  it('should include comment identifier', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain(COMMENT_IDENTIFIER);
  });

  it('should show correct line counts', () => {
    const body = generateCommentBody(
      createSummary({ addedLines: 342, removedLines: 128 }),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('**+342**');
    expect(body).toContain('**-128**');
  });

  it('should use custom header when provided', () => {
    const body = generateCommentBody(
      createSummary(),
      '## Custom Header',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('## Custom Header');
  });

  it('should include included files section', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Included (2 files');
    expect(body).toContain('src/main.ts');
    expect(body).toContain('src/utils.ts');
  });

  it('should include excluded files section when files are excluded', () => {
    const summary = createSummary({
      excludedFiles: ['dist/index.js', 'generated/api.ts'],
      excludedAddedLines: 500,
      excludedRemovedLines: 100,
    });

    const body = generateCommentBody(
      summary,
      '',
      ['**/dist/**', '**/generated/**'],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Excluded (2 files');
    expect(body).toContain('dist/index.js');
    expect(body).toContain('generated/api.ts');
    expect(body).toContain('**/dist/**');
  });

  it('should not include excluded section when no files excluded', () => {
    const body = generateCommentBody(
      createSummary({ excludedFiles: [] }),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).not.toContain('Excluded (');
  });

  it('should calculate percentages correctly', () => {
    const summary = createSummary({
      addedLines: 85,
      removedLines: 15,
      excludedAddedLines: 0,
      excludedRemovedLines: 0,
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    expect(body).toContain('100% of changes');
  });

  it('should sort files by changes descending', () => {
    const summary = createSummary({
      includedFiles: [
        {
          filename: 'small.ts',
          additions: 10,
          deletions: 5,
          changes: 15,
          status: 'modified',
        },
        {
          filename: 'large.ts',
          additions: 100,
          deletions: 50,
          changes: 150,
          status: 'modified',
        },
        {
          filename: 'medium.ts',
          additions: 30,
          deletions: 20,
          changes: 50,
          status: 'modified',
        },
      ],
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    const largeIndex = body.indexOf('large.ts');
    const mediumIndex = body.indexOf('medium.ts');
    const smallIndex = body.indexOf('small.ts');

    expect(largeIndex).toBeLessThan(mediumIndex);
    expect(mediumIndex).toBeLessThan(smallIndex);
  });

  it('should include attribution footer', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain('Generated by');
    expect(body).toContain('Lines Changed');
    expect(body).toContain('https://github.com/nrutman/lines-changed-gha');
  });

  it('should handle singular file count', () => {
    const summary = createSummary({
      includedFiles: [
        {
          filename: 'only.ts',
          additions: 10,
          deletions: 5,
          changes: 15,
          status: 'modified',
        },
      ],
    });

    const body = generateCommentBody(summary, '', [], 'owner', 'repo', 123);

    expect(body).toContain('1 file');
    expect(body).not.toContain('1 files');
  });

  it('should generate valid file diff URLs', () => {
    const body = generateCommentBody(
      createSummary(),
      '',
      [],
      'owner',
      'repo',
      123
    );

    expect(body).toContain(
      'https://github.com/owner/repo/pull/123/files#diff-'
    );
  });
});
