import type { DiffSummary, FileChange } from './types';
import { COMMENT_IDENTIFIER } from './constants';
import { generateDiffSquares } from './generateDiffSquares';
import { generateFileDiffUrl } from './generateFileDiffUrl';

function pluralize(count: number, singular: string, plural: string): string {
  return count === 1 ? singular : plural;
}

function calculatePercentage(part: number, total: number): number {
  return total > 0 ? Math.round((part / total) * 100) : 0;
}

function generateFileTable(
  files: FileChange[],
  owner: string,
  repo: string,
  prNumber: number
): string {
  const sortedFiles = [...files].sort((a, b) => b.changes - a.changes);

  let table = '| File | Lines Added | Lines Removed |\n';
  table += '|------|-------------|---------------|\n';

  for (const file of sortedFiles) {
    const fileUrl = generateFileDiffUrl(owner, repo, prNumber, file.filename);
    table += `| [\`${file.filename}\`](${fileUrl}) | +${file.additions} | -${file.deletions} |\n`;
  }

  return table;
}

export function generateCommentBody(
  summary: DiffSummary,
  header: string,
  excludePatterns: string[],
  owner: string,
  repo: string,
  prNumber: number
): string {
  const squares = generateDiffSquares(summary.addedLines, summary.removedLines);

  // Build comment body - icons and counts are always the main header
  let body = `${COMMENT_IDENTIFIER}\n`;

  // Add optional header text above the summary if provided
  if (header) {
    body += `${header}\n\n`;
  }

  body += `## ${squares} **+${summary.addedLines}** / **-${summary.removedLines}**\n\n`;

  const includedChangedLines = summary.addedLines + summary.removedLines;
  const ignoredChangedLines =
    summary.ignoredAddedLines + summary.ignoredRemovedLines;
  const totalChangedLines = includedChangedLines + ignoredChangedLines;

  const includedCount = summary.includedFiles.length;
  const ignoredCount = summary.ignoredFiles.length;

  const includedPercentage = calculatePercentage(
    includedChangedLines,
    totalChangedLines
  );
  const ignoredPercentage = calculatePercentage(
    ignoredChangedLines,
    totalChangedLines
  );

  if (includedCount > 0) {
    const changedSummary = `Changed (${includedCount} ${pluralize(includedCount, 'file', 'files')}, ${includedPercentage}% of changes)`;
    body += `<details>\n<summary>${changedSummary}</summary>\n\n`;
    body += generateFileTable(summary.includedFiles, owner, repo, prNumber);
    body += '\n</details>\n\n';
  }

  if (ignoredCount > 0) {
    const ignoredSummary = `Ignored (${ignoredCount} ${pluralize(ignoredCount, 'file', 'files')}, ${ignoredPercentage}% of changes)`;
    body += `<details>\n<summary>${ignoredSummary}</summary>\n\n`;
    body += `Ignored patterns: \`${excludePatterns.join('`, `')}\`\n\n`;
    body += generateFileTable(summary.ignoredFiles, owner, repo, prNumber);
    body += '\n</details>';
  }

  body += '\n\n---\n';
  body +=
    '*Generated by [Lines Changed](https://github.com/nrutman/lines-changed-gha) GitHub Action*';

  return body;
}
