import type { DiffSummary } from './types';
import { COMMENT_IDENTIFIER } from './constants';
import { generateDiffSquares } from './generateDiffSquares';
import { generateFileDiffUrl } from './generateFileDiffUrl';

export function generateCommentBody(
  summary: DiffSummary,
  header: string,
  excludePatterns: string[],
  owner: string,
  repo: string,
  prNumber: number
): string {
  const squares = generateDiffSquares(summary.addedLines, summary.removedLines);

  let body = `${COMMENT_IDENTIFIER}\n## ${squares} **+${summary.addedLines}** / **-${summary.removedLines}**\n\n`;

  const totalAddedLines = summary.addedLines + summary.excludedAddedLines;
  const totalRemovedLines = summary.removedLines + summary.excludedRemovedLines;
  const totalChangedLines = totalAddedLines + totalRemovedLines;
  const excludedChangedLines =
    summary.excludedAddedLines + summary.excludedRemovedLines;

  const includedCount = summary.includedFiles.length;
  const excludedCount = summary.excludedFiles.length;

  body += `**${includedCount}** ${includedCount === 1 ? 'file' : 'files'} included`;

  if (excludedCount > 0) {
    const excludedPercentage =
      totalChangedLines > 0
        ? Math.round((excludedChangedLines / totalChangedLines) * 100)
        : 0;
    body += `, **${excludedCount}** ${excludedCount === 1 ? 'file' : 'files'} excluded`;
    body += ` (${excludedPercentage}% of changes)\n\n`;
  } else {
    body += '\n\n';
  }

  if (excludedCount > 0) {
    body += '<details>\n<summary>Excluded files</summary>\n\n';
    body += `The following files were excluded based on patterns: \`${excludePatterns.join('`, `')}\`\n\n`;
    body += `**Total excluded:** +${summary.excludedAddedLines} / -${summary.excludedRemovedLines} lines\n\n`;

    for (const filename of summary.excludedFiles) {
      const fileUrl = generateFileDiffUrl(owner, repo, prNumber, filename);
      body += `- [\`${filename}\`](${fileUrl})\n`;
    }

    body += '\n</details>\n\n';
  }

  if (includedCount > 0) {
    body += '<details>\n<summary>Files included in summary</summary>\n\n';
    body += '| File | Lines Added | Lines Removed |\n';
    body += '|------|-------------|---------------|\n';

    const sortedFiles = [...summary.includedFiles].sort(
      (a, b) => b.changes - a.changes
    );

    for (const file of sortedFiles) {
      const fileUrl = generateFileDiffUrl(owner, repo, prNumber, file.filename);
      body += `| [\`${file.filename}\`](${fileUrl}) | +${file.additions} | -${file.deletions} |\n`;
    }

    body += '\n</details>';
  }

  body += '\n\n---\n';
  body +=
    '*Generated by [Lines Changed](https://github.com/nrutman/lines-changed-gha) GitHub Action*';

  return body;
}
