import { COMMENT_IDENTIFIER } from './constants';
import { generateDiffSquares } from './generateDiffSquares';
import { generateFileDiffUrl } from './generateFileDiffUrl';
import type { DiffSummary, FileChange, GroupedFiles } from './types';
import { isFileGroup } from './types';

export function generateCommentBody(
  summary: DiffSummary,
  header: string,
  owner: string,
  repo: string,
  prNumber: number,
  headSha: string
): string {
  const squares = generateDiffSquares(summary.addedLines, summary.removedLines);

  // Build comment body - icons and counts are always the main header
  let body = `${COMMENT_IDENTIFIER}\n`;

  // Add optional header text above the summary if provided
  if (header) {
    body += `${header}\n\n`;
  }

  body += `## ${squares} **+${summary.addedLines}** / **-${summary.removedLines}**\n\n`;

  // Calculate total changed lines across all groups for percentage calculations
  const totalChangedLines =
    summary.addedLines +
    summary.removedLines +
    summary.uncountedAddedLines +
    summary.uncountedRemovedLines;

  // Determine if we should show count indicators (only if there's a mix of counted/uncounted groups)
  const hasCountedGroups = summary.groupedFiles.some(
    g => g.group.countTowardMetric && g.files.length > 0
  );
  const hasUncountedGroups = summary.groupedFiles.some(
    g => !g.group.countTowardMetric && g.files.length > 0
  );
  const showCountIndicator = hasCountedGroups && hasUncountedGroups;

  // Determine if any group uses ignore-whitespace
  const showWhitespaceIndicator = summary.groupedFiles.some(
    g => isFileGroup(g.group) && g.group.ignoreWhitespace && g.files.length > 0
  );

  // Generate sections for each group with files
  const groupSections: string[] = [];
  for (const groupedFile of summary.groupedFiles) {
    if (groupedFile.files.length > 0) {
      groupSections.push(
        generateGroupSection(
          groupedFile,
          totalChangedLines,
          owner,
          repo,
          prNumber,
          showCountIndicator,
          showWhitespaceIndicator
        )
      );
    }
  }

  body += groupSections.join('\n\n');

  const shortSha = headSha.slice(0, 7);
  const commitUrl = `https://github.com/${owner}/${repo}/commit/${headSha}`;

  body += '\n\n---\n';

  // Add footnotes above attribution
  if (showCountIndicator) {
    body += '\\* *Not counted toward the main +/- metric*\n\n';
  }
  if (showWhitespaceIndicator) {
    body += '† *Whitespace-only changes are excluded from counts*\n\n';
  }

  body += `*Generated by [Lines Changed](https://github.com/nrutman/lines-changed-gha) GitHub Action against [\`${shortSha}\`](${commitUrl})*`;

  return body;
}

// Private helpers

function pluralize(count: number, singular: string, plural: string): string {
  return count === 1 ? singular : plural;
}

function calculatePercentage(part: number, total: number): number {
  return total > 0 ? Math.round((part / total) * 100) : 0;
}

function generateFileTable(
  files: FileChange[],
  owner: string,
  repo: string,
  prNumber: number
): string {
  const sortedFiles = [...files].sort((a, b) => b.changes - a.changes);

  let table = '| File | Lines Added | Lines Removed |\n';
  table += '|------|-------------|---------------|\n';

  for (const file of sortedFiles) {
    const fileUrl = generateFileDiffUrl(owner, repo, prNumber, file.filename);
    table += `| [\`${file.filename}\`](${fileUrl}) | +${file.additions} | -${file.deletions} |\n`;
  }

  return table;
}

function generateGroupSection(
  groupedFile: GroupedFiles,
  totalChangedLines: number,
  owner: string,
  repo: string,
  prNumber: number,
  showCountIndicator: boolean,
  showWhitespaceIndicator: boolean
): string {
  const fileCount = groupedFile.files.length;
  const groupChangedLines = groupedFile.addedLines + groupedFile.removedLines;
  const percentage = calculatePercentage(groupChangedLines, totalChangedLines);

  const groupIgnoresWhitespace =
    isFileGroup(groupedFile.group) && groupedFile.group.ignoreWhitespace;

  // Build the summary line with optional markers
  const countIndicator =
    showCountIndicator && !groupedFile.group.countTowardMetric ? '*' : '';
  const whitespaceIndicator =
    showWhitespaceIndicator && groupIgnoresWhitespace ? '†' : '';
  const summaryText = `${groupedFile.group.label} (${fileCount} ${pluralize(fileCount, 'file', 'files')}, ${percentage}% of changes)${countIndicator}${whitespaceIndicator}`;

  let section = `<details>\n<summary>${summaryText}</summary>\n\n`;

  // Show patterns if this is a FileGroup (not the default group)
  if (isFileGroup(groupedFile.group)) {
    section += `Patterns: \`${groupedFile.group.patterns.join('`, `')}\`\n\n`;
  }

  section += generateFileTable(groupedFile.files, owner, repo, prNumber);
  section += '\n</details>';

  return section;
}
